noReplace: true

imports:
  - path: github.com/hbstack/contact
    version: v0.3.0
  - path: github.com/hbstack/google-fonts
    version: v0.1.1

  # icons modules
  - path: github.com/hugomods/icons/vendors/font-awesome
    version: v0.6.12
  - path: github.com/hugomods/icons/vendors/tabler
    version: v0.15.51

  # blog table of contents scrollspy
  - path: github.com/hbstack/blog/modules/toc-scrollspy
    version: v0.2.0

  # docs table of contents scrollspy
  - path: github.com/hbstack/docs/modules/toc-scrollspy
    version: v0.1.8

  # home page banner
  - path: github.com/hbstack/header/modules/banner
    version: v0.7.2

  # Animated text
  - path: github.com/hugomods/aos
    version: v0.1.0

  # recommended modules
  - path: github.com/hbstack/back-to-top
    version: v0.2.0
  - path: github.com/hbstack/code-block-panel
    version: v0.1.2
  - path: github.com/hbstack/docs
    version: v0.23.0
  - path: github.com/hbstack/docs/modules/breadcrumb
    version: v0.1.10
  - path: github.com/hbstack/docs/modules/featured-image
    version: v0.2.8
  - path: github.com/hbstack/docs/modules/heading-sign
    version: v0.1.9
  - path: github.com/hbstack/docs/modules/doc-nav
    version: v0.3.7
  - path: github.com/hbstack/blog
    version: v0.40.0
  - path: github.com/hbstack/blog/modules/breadcrumb
    version: v0.1.23
  - path: github.com/hbstack/blog/modules/featured-image
    version: v0.2.21
  - path: github.com/hbstack/blog/modules/heading-sign
    version: v0.1.23
  - path: github.com/hbstack/mermaid
    version: v0.2.2
  - path: github.com/hugomods/katex
    version: v0.3.6
  - path: github.com/hbstack/bootstrap
    version: v0.2.2
  - path: github.com/hugomods/shortcodes
    version: v0.24.0
  - path: github.com/hbstack/footer
    version: v0.4.1
  - path: github.com/hbstack/footer/modules/socials
    version: v0.3.0
  - path: github.com/hbstack/header
    version: v0.16.6
  - path: github.com/hbstack/header/modules/language-picker
    version: v0.2.0
  - path: github.com/hbstack/header/modules/socials
    version: v0.2.2
  - path: github.com/hbstack/header/modules/search
    version: v0.1.38
  - path: github.com/hugomods/seo/modules/alternatives
    version: v0.1.1
  - path: github.com/hugomods/seo/modules/base
    version: v0.1.3
  - path: github.com/hugomods/seo/modules/favicons
    version: v0.2.2
  - path: github.com/hugomods/seo/modules/open-graph
    version: v0.1.1
  - path: github.com/hugomods/seo/modules/schema
    version: v0.1.3
  - path: github.com/hugomods/seo/modules/translations
    version: v0.1.1
  - path: github.com/hugomods/seo/modules/twitter-cards
    version: v0.1.1
  - path: github.com/hbstack/syntax-highlighting/styles/gruvbox
    version: v0.1.2
  - path: github.com/hbstack/noscript
    version: v0.7.0
  - path: github.com/hbstack/progress-bar
    version: v0.1.1
  - path: github.com/hbstack/scrollbar
    version: v0.1.0