# For some regions can not access the proxy.golang.org, i.e. China.
# See https://hugomods.com/en/blog/2023/04/go-and-hugo-proxy-servers/ for all available proxy servers.
# proxy: https://goproxy.cn,direct

# The order of module is very important, precedence from top to bottom.
imports:
  # - path: github.com/hugomods/bootstrap/modules/decap-cms
  # - path: github.com/hbstack/blog/modules/decap-cms
  # - path: github.com/hbstack/docs/modules/decap-cms
  # - path: github.com/hbstack/decap-cms
  # - path: github.com/hugomods/decap-cms/widgets/url
  # - path: github.com/hugomods/decap-cms/editor-components/todo
  # - path: github.com/hugomods/decap-cms

  - path: github.com/hbstack/contact

  - path: github.com/hbstack/google-fonts
  # gallery modules.
  - path: github.com/hbstack/gallery
  - path: github.com/hbstack/gallery/modules/breadcrumb

  # icons modules
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/icons/vendors/tabler

  # blog sidebar
  # - path: github.com/hbstack/blog/modules/sidebar/profile
  # - path: github.com/hbstack/blog/modules/sidebar/posts
  # - path: github.com/hbstack/blog/modules/sidebar/taxonomies

  # blog table of contents scrollspy
  - path: github.com/hbstack/blog/modules/toc-scrollspy

  # blog content panel
  - path: github.com/hbstack/blog/modules/content-panel

  # docs table of contents scrollspy
  - path: github.com/hbstack/docs/modules/toc-scrollspy

  # docs content panel
  # - path: github.com/hbstack/docs/modules/content-panel

  # home page banner
  - path: github.com/hbstack/header/modules/banner

  # Animated text
  - path: github.com/hugomods/aos

  # recommended modules
  - path: github.com/hbstack/back-to-top
  - path: github.com/hbstack/bigger-picture
  - path: github.com/hbstack/code-block-panel
  - path: github.com/hbstack/docs
  - path: github.com/hbstack/docs/modules/breadcrumb
  - path: github.com/hbstack/docs/modules/featured-image
  - path: github.com/hbstack/docs/modules/heading-sign
  - path: github.com/hbstack/docs/modules/doc-nav
  - path: github.com/hbstack/blog
  - path: github.com/hbstack/blog/modules/breadcrumb
  - path: github.com/hbstack/blog/modules/featured-image
  - path: github.com/hbstack/blog/modules/heading-sign
  - path: github.com/hbstack/blog/modules/post-nav
  - path: github.com/hbstack/blog/modules/related-posts
  - path: github.com/hbstack/mermaid
  - path: github.com/hugomods/katex
  - path: github.com/hbstack/bootstrap
  - path: github.com/hugomods/images
  - path: github.com/hugomods/shortcodes
  - path: github.com/hbstack/footer
  - path: github.com/hbstack/footer/modules/socials
  - path: github.com/hbstack/header
  - path: github.com/hbstack/header/modules/language-picker
  - path: github.com/hbstack/header/modules/socials
  - path: github.com/hbstack/header/modules/search
  - path: github.com/hugomods/seo/modules/alternatives
  - path: github.com/hugomods/seo/modules/base
  - path: github.com/hugomods/seo/modules/favicons
  - path: github.com/hugomods/seo/modules/open-graph
  - path: github.com/hugomods/seo/modules/schema
  - path: github.com/hugomods/seo/modules/translations
  - path: github.com/hugomods/seo/modules/twitter-cards
  - path: github.com/hbstack/syntax-highlighting/styles/gruvbox
  - path: github.com/hbstack/noscript
  - path: github.com/hbstack/progress-bar
  - path: github.com/hbstack/pwa
  - path: github.com/hbstack/scrollbar

