name: GitHub Pages - Staging

on:
  # Trigger deployment on push to the staging branch
  push:
    branches:
      - staging

  # Allow manual deployment as well
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:exts-0.145.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install Node.js dependencies
        run: npm ci
        shell: sh

      - name: Add repository to Git safe directory
        run: git config --global --add safe.directory /__w/IJC-BIT_web_staging/IJC-BIT_web_staging
        shell: sh

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        shell: sh
        run: |
          hugo \
            --gc \
            --enableGitInfo \
            --minify \
            -e production \
            --baseURL "${{ steps.pages.outputs.base_url }}/"  
            
      - name: Debug Build Output
        run: ls -R public
        shell: sh        
      
      - name: Install GNU tar
        run: apk add --no-cache tar
        shell: sh          

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages-staging
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
